import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Setup & Core Concepts',
      items: [
        'getting-started',
        'Architecture',
        'menuhandler',
        'breadcrumbshandler'
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        { type: 'autogenerated', dirName: 'Tutorials' }
      ],
    },
    {
      type: 'category',
      label: 'UIMenu (Main Menu)',
      items: [
        'UIMenu/index',
        'UIMenu/Parameters',
        'UIMenu/Functions',
        'UIMenu/Events',
        { type: 'autogenerated', dirName: 'UIMenu/Items' },
        { type: 'autogenerated', dirName: 'UIMenu/Panels' },
        { type: 'autogenerated', dirName: 'UIMenu/Windows' },
        { type: 'autogenerated', dirName: 'UIMenu/Side Panels' }
      ],
    },
    {
      type: 'category',
      label: 'Specialized Menus',
      items: [
        { type: 'autogenerated', dirName: 'PauseMenu' },
        { type: 'autogenerated', dirName: 'RadialMenu' },
        { type: 'autogenerated', dirName: 'RadioMenu' }
      ],
    },
    {
      type: 'category',
      label: 'Screen Elements',
      items: [
        { type: 'autogenerated', dirName: 'hud' },
        { type: 'autogenerated', dirName: 'Scaleforms' },
        { type: 'autogenerated', dirName: 'TimerBars' },
        { type: 'autogenerated', dirName: 'Elements' }
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        { type: 'autogenerated', dirName: 'Enums' }
      ],
    }
  ],
};

export default sidebars;
